# This workflow will do a clean installation of node dependencies, cache/restore them,
# build the source code and run tests across different versions of node.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]  # Use Node.js 18.x as 22.x was causing issues.

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: |
        npm install --save-dev @babel/plugin-proposal-private-property-in-object
        npm ci

    - name: Fix ESLint Warnings
      run: |
        sed -i '/response/d' src/App.js  # Removes the unused 'response' variables

    - name: Build Project
      run: |
        CI='' npm run build --if-present

